import { StrictMode, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { ArrowRight, BookOpen, Check, ChevronDown, ChevronRight, CircleAlert, Copy, Menu, Search, ShieldCheck, Terminal, X } from "lucide-react";
import { endpoints, errors, navigation, scopes, type Endpoint } from "./docsCatalog";
import { requestContracts } from "./openapiRequestSchemas.generated";
import { DeveloperAuthProvider, DeveloperForgotPassword, DeveloperLogin, DeveloperResetPassword, DeveloperSignup, DeveloperVerifyEmail, ProtectedDeveloperPage, useDeveloperAuth } from "./developerAuth";
import "./styles.css";

const apiBaseUrl = (import.meta.env.VITE_API_URL || "https://api.exaearn.com").replace(/\/$/, "");

function usePath() {
  const currentPath = () => { const value = window.location.pathname.replace(/\/+$/, "") || "/"; return value === "/" ? "/developers" : value; };
  const [path, setPath] = useState(currentPath);
  useEffect(() => { const update = () => setPath(currentPath()); window.addEventListener("popstate", update); return () => window.removeEventListener("popstate", update); }, []);
  return path;
}
function go(path: string) { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo({ top: 0, behavior: "instant" }); }
function Link({ to, children, className = "", onClick }: { to: string; children: ReactNode; className?: string; onClick?: () => void }) { return <a href={to} className={className} onClick={(event) => { event.preventDefault(); go(to); onClick?.(); }}>{children}</a>; }

function App() {
  return <DeveloperAuthProvider><Portal /></DeveloperAuthProvider>;
}

function Portal() {
  const path = usePath(); const docsMode = path.startsWith("/docs") || path.startsWith("/reference");
  const authMode = path === "/developers/login"; const signupMode = path === "/developers/signup"; const verifyMode = path === "/developers/verify-email"; const forgotMode = path === "/developers/forgot-password"; const resetMode = path === "/developers/reset-password"; const invitationMode = path === "/developers/invitations/accept"; const consoleMode = path.startsWith("/developers/console") || path === "/developers/onboarding" || invitationMode;
  const [menuOpen, setMenuOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false);
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setSearchOpen(true); } }; window.addEventListener("keydown", shortcut); return () => window.removeEventListener("keydown", shortcut); }, []);
  if (authMode) return <DeveloperLogin />;
  if (signupMode) return <DeveloperSignup />;
  if (verifyMode) return <DeveloperVerifyEmail />;
  if (forgotMode) return <DeveloperForgotPassword />;
  if (resetMode) return <DeveloperResetPassword />;
  if (consoleMode) return <ProtectedDeveloperPage onboarding={path === "/developers/onboarding"} security={path === "/developers/console/settings/security"} team={path === "/developers/console/team"} apiKeys={path === "/developers/console/api-keys"} productionAccess={path === "/developers/console/production-access"} invitation={invitationMode} />;
  return <div className={docsMode ? "app docs-mode" : "app"}>
    <Header docsMode={docsMode} onMenu={() => setMenuOpen(true)} onSearch={() => setSearchOpen(true)} />
    {docsMode ? <div className="docs-grid"><Sidebar path={path} open={menuOpen} close={() => setMenuOpen(false)} /><main className="doc-content"><RouteContent path={path} /></main><OnPageToc path={path} /></div> : <Landing />}
    {searchOpen && <SearchDialog close={() => setSearchOpen(false)} />}
  </div>;
}

function Header({ docsMode, onMenu, onSearch }: { docsMode: boolean; onMenu: () => void; onSearch: () => void }) {
  const { session, loading, signOut } = useDeveloperAuth();
  return <header className="site-header"><button className="icon-button menu-button" onClick={onMenu} aria-label="Open documentation navigation"><Menu size={19} /></button><Link to="/developers" className="brand"><span className="brand-mark">EX</span><span><strong>ExaEarn</strong><small>Developers</small></span></Link><nav className="top-nav" aria-label="Developer portal"><Link to="/docs" className={docsMode ? "active" : ""}>Docs</Link><Link to="/reference/exchange-info">API Reference</Link><Link to="/docs/sdks">SDKs</Link><Link to="/docs/sandbox">Sandbox</Link><Link to="/docs/changelog">Changelog</Link><Link to="/docs/status">Status</Link></nav><button className="search-trigger" onClick={onSearch}><Search size={16} /><span>Search docs</span><kbd>Ctrl K</kbd></button>{!loading && (session ? <details className="user-menu"><summary><span>{session.user.name.slice(0, 1).toUpperCase()}</span> Console <ChevronDown size={14} /></summary><div><Link to="/developers/console">Developer Console</Link><a href="https://app.exaearn.com/settings/security">Account security</a><a href="https://app.exaearn.com">Go to ExaEarn</a><button onClick={() => void signOut()}>Sign out</button></div></details> : <div className="header-auth"><Link to="/developers/login">Sign in</Link><Link to="/developers/signup" className="console-link">Start building</Link></div>)}</header>;
}

function Landing() {
  return <main className="landing"><section className="landing-hero"><div><p className="eyebrow">ExaEarn Developer Platform</p><h1>Build directly on ExaEarn.</h1><p className="lead">Production contracts for market data, trading, accounts, realtime events, and webhooks, backed by the same canonical systems used by ExaEarn.</p><div className="actions"><Link to="/docs/quickstart" className="primary">Start building <ArrowRight size={17} /></Link><Link to="/reference/exchange-info" className="secondary">API reference</Link></div></div><CodeSample title="Query server time" code={`curl ${apiBaseUrl}/api/developer/v1/time`} /></section><section className="foundation-grid"><Feature icon={<BookOpen />} title="Complete contracts">Authentication, parameters, responses, errors, limits, lifecycle, and recovery.</Feature><Feature icon={<ShieldCheck />} title="Canonical execution">Developer orders use existing OMS, risk, reservations, settlement, and ledger paths.</Feature><Feature icon={<Terminal />} title="Sandbox first">`exa_test_` credentials and isolated balances protect production financial state.</Feature></section><section className="landing-section"><p className="eyebrow">Core APIs</p><h2>From first request to production integration.</h2><div className="product-grid">{[["Market data", "Public tickers, books, trades, and execution-built candles.", "/reference/tickers"], ["Spot", "Submit and inspect orders through ExaEarn Spot OMS.", "/reference/spot-create-order"], ["Futures", "Controlled access to positions and risk-checked execution.", "/reference/futures-create-order"], ["Realtime", "Sequenced streams, replay, and documented resynchronization.", "/reference/realtime-session"]].map(([title, detail, to]) => <Link key={title} to={to} className="product-card"><h3>{title}</h3><p>{detail}</p><span>Read documentation <ChevronRight size={15} /></span></Link>)}</div></section><section className="cta-strip"><div><h2>Make your first request in under five minutes.</h2><p>Start with public market data, then create an isolated sandbox project.</p></div><Link to="/docs/quickstart" className="primary">Open quickstart <ArrowRight size={17} /></Link></section></main>;
}

function Sidebar({ path, open, close }: { path: string; open: boolean; close: () => void }) { const closeButton = useRef<HTMLButtonElement>(null); useEffect(() => { if (!open) return; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; closeButton.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; window.addEventListener("keydown", escape); return () => { document.body.style.overflow = previousOverflow; window.removeEventListener("keydown", escape); document.querySelector<HTMLButtonElement>(".menu-button")?.focus(); }; }, [open, close]); return <><button className={`drawer-backdrop ${open ? "show" : ""}`} onClick={close} aria-label="Close navigation" /><aside className={`sidebar ${open ? "open" : ""}`} aria-label="Documentation navigation" aria-modal={open || undefined} role={open ? "dialog" : undefined}><div className="sidebar-mobile-title"><strong>Documentation</strong><button ref={closeButton} className="icon-button" onClick={close} aria-label="Close documentation navigation"><X size={18} /></button></div>{navigation.map(([group, links]) => <section key={group}><h2>{group}</h2>{links.map(([label, to]) => <Link key={to} to={to} onClick={close} className={path === to ? "active" : ""}>{label}</Link>)}</section>)}</aside></>; }

function RouteContent({ path }: { path: string }) {
  if (path.startsWith("/reference/")) { const endpoint = endpoints.find((item) => item.id === path.split("/").pop()); return endpoint ? <EndpointPage endpoint={endpoint} /> : <NotFound />; }
  const routes: Record<string, ReactNode> = { "/docs/quickstart": <Quickstart />, "/docs/environments": <Environments />, "/docs/authentication": <Authentication />, "/docs/scopes": <Scopes />, "/docs/rate-limits": <RateLimits />, "/docs/errors": <Errors />, "/docs/precision": <Precision />, "/docs/orderbook-recovery": <OrderBookRecovery />, "/docs/webhooks": <Webhooks />, "/docs/sdks": <Sdks />, "/docs/sandbox": <Sandbox />, "/docs/changelog": <Changelog />, "/docs/status": <Status /> };
  return routes[path] || <Overview />;
}
function DocHead({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <header className="doc-head"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{children}</p></header>; }

function Overview() { return <><DocHead eyebrow="Getting started" title="ExaEarn API documentation">Integrate public market data, signed account APIs, controlled trading products, durable realtime streams, and signed webhooks.</DocHead><Callout>Public documentation and market data do not require KYC. Production private APIs require an approved account, appropriate verification, and explicitly scoped production credentials.</Callout><h2 id="architecture">One financial authority</h2><p>Developer requests enter the same controllers and canonical services used by ExaEarn applications. The API does not maintain a separate ledger, matching engine, risk system, or wallet.</p><Flow items={["Developer request", "Authentication + scope", "Validation + risk", "Canonical product service", "Ledger / OMS authority", "REST + realtime result"]} /><h2 id="next">Choose a starting point</h2><div className="link-list"><Link to="/docs/quickstart">5-minute sandbox quickstart <ArrowRight size={15} /></Link><Link to="/docs/authentication">Implement HMAC signing <ArrowRight size={15} /></Link><Link to="/reference/spot-create-order">Create a Spot order <ArrowRight size={15} /></Link></div></>; }
function Quickstart() { return <><DocHead eyebrow="Getting started" title="5-minute quickstart">Prove connectivity, synchronize time, create a sandbox project and submit your first isolated Spot order.</DocHead><Steps items={["Sign in and create a Developer project.", "Select Sandbox. New developers should start here.", "Generate an `exa_test_` key with market, account, Spot read, and Spot trade scopes.", "Store the secret once in a server-side environment variable.", "Query server time and correct local clock drift.", "Fund isolated test balances using the project faucet.", "Submit a sandbox Spot order with a unique client_order_id.", "Create a realtime session for order, trade, and account.balance."]} /><CodeTabs samples={{ cURL: `curl ${apiBaseUrl}/api/developer/v1/time`, TypeScript: `import { createExaEarnClient } from "@exaearn/sdk";\n\nconst client = createExaEarnClient({ baseUrl: "${apiBaseUrl}" });\nconst time = await client.getServerTime();`, Python: `import requests\n\ntime = requests.get("${apiBaseUrl}/api/developer/v1/time").json()` }} /><Callout tone="warning">Never place an API secret in browser or mobile application code. Signed private requests belong on your trusted server.</Callout></>; }
function Environments() { return <><DocHead eyebrow="Getting started" title="Environments">Sandbox and production are isolated at the project, credential, balance, and event level.</DocHead><table><thead><tr><th>Environment</th><th>Key prefix</th><th>Financial state</th><th>Access</th></tr></thead><tbody><tr><td>Sandbox</td><td><code>exa_test_</code></td><td>Isolated test balances</td><td>Default</td></tr><tr><td>Production</td><td><code>exa_live_</code></td><td>Canonical ExaEarn accounts</td><td>Verification and approval</td></tr></tbody></table><h2 id="urls">Base URLs</h2><CodeSample title="REST" code={`${apiBaseUrl}/api/developer/v1`} /><p>Realtime connection URLs are returned by the environment-aware session flow. Sandbox credentials cannot authenticate production projects.</p></>; }
function Authentication() { const canonical = `METHOD.toUpperCase() + "\\n" +\nPATH + "\\n" +\nRAW_QUERY_STRING + "\\n" +\nUNIX_TIMESTAMP_SECONDS + "\\n" +\nUNIQUE_NONCE + "\\n" +\nSHA256_HEX(RAW_BODY)`; return <><DocHead eyebrow="Security" title="HMAC request authentication">Every private request proves possession of an active project key without sending its secret.</DocHead><h2 id="headers">Required headers</h2><table><thead><tr><th>Header</th><th>Value</th></tr></thead><tbody>{[["EXA-API-KEY", "Environment API key"], ["EXA-API-TIMESTAMP", "Unix seconds; ±300 seconds"], ["EXA-API-NONCE", "Unique per key"], ["EXA-API-SIGNATURE", "Lowercase hex HMAC-SHA256"], ["EXA-API-PASSPHRASE", "Only when configured"]].map(([a,b]) => <tr key={a}><td><code>{a}</code></td><td>{b}</td></tr>)}</tbody></table><h2 id="canonical">Canonical payload</h2><CodeSample title="Signing input" code={canonical} /><CodeTabs samples={{ TypeScript: `const bodyHash = await sha256Hex(rawBody);\nconst canonical = [method.toUpperCase(), path, rawQuery, timestamp, nonce, bodyHash].join("\\n");\nconst signature = await hmacSha256Hex(secret, canonical);`, Python: `body_hash = hashlib.sha256(raw_body.encode()).hexdigest()\ncanonical = "\\n".join([method.upper(), path, raw_query, timestamp, nonce, body_hash])\nsignature = hmac.new(secret.encode(), canonical.encode(), hashlib.sha256).hexdigest()`, PHP: `$bodyHash = hash('sha256', $rawBody);\n$canonical = implode("\\n", [strtoupper($method), $path, $query, $timestamp, $nonce, $bodyHash]);\n$signature = hash_hmac('sha256', $canonical, $secret);` }} /><Callout tone="warning">Sign the raw query string and exact serialized body sent over the wire. Reserializing after signing causes <code>INVALID_SIGNATURE</code>.</Callout></>; }
function Scopes() { return <><DocHead eyebrow="Security" title="Permissions and scopes">Grant each key only the minimum capabilities its integration needs.</DocHead><table><thead><tr><th>Scope</th><th>Risk</th><th>Capability</th></tr></thead><tbody>{scopes.map(([scope,risk,detail]) => <tr key={scope}><td><code>{scope}</code></td><td><StatusBadge value={risk === "RESTRICTED" ? "RESTRICTED" : risk === "HIGH" ? "BETA" : "STABLE"} label={risk} /></td><td>{detail}</td></tr>)}</tbody></table><Callout tone="warning"><code>wallet.withdraw</code> remains restricted, requires an IP allowlist, and is not general public access.</Callout></>; }
function RateLimits() { return <><DocHead eyebrow="API behavior" title="Rate limits">Budgets protect the exchange and are evaluated by route group and credential context.</DocHead><table><thead><tr><th>Class</th><th>Budget</th></tr></thead><tbody><tr><td>Public REST</td><td>240/minute</td></tr><tr><td>Private REST</td><td>120/minute</td></tr><tr><td>Trading writes</td><td>60/minute</td></tr><tr><td>Withdrawal</td><td>10/minute</td></tr></tbody></table><p>Honor <code>Retry-After</code>, use jittered backoff, and never retry a financial write without its idempotency identity.</p></>; }
function Errors() { return <><DocHead eyebrow="API behavior" title="Error code reference">Machine-readable failures include the request ID needed for support correlation.</DocHead><CodeSample title="Error envelope" code={`{\n  "success": false,\n  "error": {\n    "code": "INVALID_SIGNATURE",\n    "message": "API request signature is invalid.",\n    "request_id": "exa_req_...",\n    "details": {}\n  },\n  "timestamp": 1787990400000\n}`} /><table><thead><tr><th>Code</th><th>HTTP</th><th>Meaning</th><th>Retry</th></tr></thead><tbody>{errors.map(([code,status,meaning,retry]) => <tr key={code}><td><code>{code}</code></td><td>{status}</td><td>{meaning}</td><td>{retry}</td></tr>)}</tbody></table></>; }
function Precision() { return <><DocHead eyebrow="API behavior" title="Decimal and precision rules">Treat all financial decimal fields as strings from input through reconciliation.</DocHead><ul><li>Never calculate price, quantity, fee, volume, collateral, or PnL with binary floating point.</li><li>Read tick size, step size, minimum quantity, and minimum notional from exchange metadata.</li><li>Reject locally invalid input before submission, while treating server validation as authoritative.</li></ul></>; }

function EndpointPage({ endpoint }: { endpoint: Endpoint }) { const curl = `${endpoint.method === "GET" ? "curl" : "curl -X " + endpoint.method} '${apiBaseUrl}${endpoint.path}'${endpoint.auth === "Signed" ? " \\\n  -H 'EXA-API-KEY: exa_test_...' \\\n  -H 'EXA-API-TIMESTAMP: ...' \\\n  -H 'EXA-API-NONCE: ...' \\\n  -H 'EXA-API-SIGNATURE: ...'" : ""}${endpoint.body ? ` \\\n  -H 'Content-Type: application/json' \\\n  --data '${endpoint.body.replace(/\n/g, "")}'` : ""}`; return <><DocHead eyebrow={endpoint.group} title={endpoint.title}>{endpoint.description}</DocHead><div className="endpoint-title"><span className={`method ${endpoint.method.toLowerCase()}`}>{endpoint.method}</span><code>{endpoint.path}</code><StatusBadge value={endpoint.status} /></div><dl className="contract-grid"><Meta label="Environment" value="Sandbox / Production" /><Meta label="Authentication" value={endpoint.auth} /><Meta label="Required scope" value={endpoint.scope || "None"} /><Meta label="Rate limit" value={endpoint.rate} /><Meta label="Idempotency" value={endpoint.idempotency} /><Meta label="Content type" value={endpoint.body ? "application/json" : "Not applicable"} /></dl>{endpoint.parameters && <><h2 id="parameters">Parameters</h2><table><thead><tr><th>Name</th><th>Type</th><th>Requirement</th><th>Description</th></tr></thead><tbody>{endpoint.parameters.map(([name,type,required,detail]) => <tr key={name}><td><code>{name}</code></td><td>{type}</td><td>{required}</td><td>{detail}</td></tr>)}</tbody></table></>}{endpoint.body && <><h2 id="request">Request body</h2><CodeSample title="application/json" code={endpoint.body} /></>}<h2 id="example">Example request</h2><CodeTabs samples={{ cURL: curl, TypeScript: `// Use the matching typed @exaearn/sdk product method.\nconst result = await client.${endpoint.id.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())}();`, Python: `response = requests.${endpoint.method.toLowerCase()}("${apiBaseUrl}${endpoint.path}")` }} /><h2 id="response">Successful response</h2><CodeSample title="application/json" code={endpoint.response} />{endpoint.events && <><h2 id="events">Associated realtime streams</h2><div className="chip-row">{endpoint.events.map((event) => <code key={event}>{event}</code>)}</div></>}<TrySandbox endpoint={endpoint} /></>; }
function OrderBookRecovery() { return <><DocHead eyebrow="WebSocket" title="Order book snapshot and delta recovery">Maintain a local book only when every sequence after the authoritative snapshot is contiguous.</DocHead><Flow items={["Buffer incoming deltas", "Fetch REST snapshot at N", "Discard deltas ≤ N", "Apply N+1 onward", "On gap: invalidate and resync"]} /><CodeSample title="Gap-safe pseudocode" code={`buffer(delta)\nsnapshot = GET /orderbook/BTC-USDT\nbook.replace(snapshot)\nfor delta in buffered.where(sequence > snapshot.sequence):\n  if delta.sequence !== book.sequence + 1:\n    book.invalidate()\n    return resync()\n  book.apply(delta)`} /><Callout tone="warning">Do not invent missing levels or apply a delta across a sequence gap. Quantity zero removes a price level.</Callout></>; }
function Webhooks() { return <><DocHead eyebrow="Webhooks" title="Signed event delivery">Receive financial lifecycle events with stable event IDs, retries, dead-letter handling, and replay.</DocHead><CodeSample title="Envelope" code={`{\n  "event_id": "evt_...",\n  "event_type": "order.filled",\n  "created_at": "2026-08-29T00:00:00Z",\n  "data": {}\n}`} /><h2 id="verify">Verify signatures</h2><p>Compute lowercase HMAC-SHA256 over <code>timestamp + "." + rawBody</code> using the separate <code>whsec_</code> secret. Compare in constant time.</p><h2 id="delivery">Delivery lifecycle</h2><Flow items={["PENDING", "DELIVERING", "DELIVERED / RETRYING", "8 attempts", "DEAD_LETTERED", "Replay"]} /><p>Replay keeps the stable event ID so consumers deduplicate without recreating an ExaEarn financial event.</p></>; }
function Sdks() { return <><DocHead eyebrow="SDKs" title="TypeScript SDK">Typed public requests, private signing, nonce generation, product helpers, and normalized errors.</DocHead><CodeSample title="Install" code="pnpm add @exaearn/sdk" /><CodeTabs samples={{ TypeScript: `import { createExaEarnClient } from "@exaearn/sdk";\nconst client = createExaEarnClient({ baseUrl: process.env.EXAEARN_API_URL! });\nconst time = await client.getServerTime();`, cURL: `curl ${apiBaseUrl}/api/developer/v1/tickers`, Python: `# Python SDK is not published yet. Use the documented REST contract.\nimport requests` }} /><Callout>Python SDK remains unpublished. The portal does not claim a package until its release and contract tests exist.</Callout></>; }
function Sandbox() { return <><DocHead eyebrow="Sandbox" title="Isolated integration testing">Sandbox projects use separate credentials, balances, events, and faucet limits.</DocHead><p>The project faucet writes only to <code>developer_sandbox_balances</code>. Sandbox cannot mutate production wallets, orders, positions, treasury, or custody.</p><Callout tone="warning">Sandbox behavior is not evidence of production liquidity, provider availability, chain settlement, or fills.</Callout></>; }
function Changelog() { return <><DocHead eyebrow="Operations" title="API changelog">Compatibility notices for the versioned Developer API.</DocHead><article className="change"><time>2026-08-29</time><StatusBadge value="STABLE" label="Added" /><h2>Server time and documentation architecture</h2><p>Added server time, canonical error timestamps, searchable reference pages, and recovery contracts. Non-breaking.</p></article></>; }
function Status() { const rows = [["Public market REST", "STABLE", "Authoritative internal and labeled reference sources"], ["Spot private REST", "STABLE", "Canonical OMS and settlement"], ["Futures", "RESTRICTED", "Controlled rollout"], ["Margin", "RESTRICTED", "Controlled rollout"], ["Staking", "STABLE", "Software ready; mainnet provider setup remains external"], ["Copy Trading", "RESTRICTED", "Eligibility and risk controls apply"], ["ExaAI", "RESTRICTED", "Governance and kill switches apply"], ["Webhooks", "STABLE", "Signed retry, DLQ, replay"], ["Live uptime telemetry", "BETA", "Not yet published"]] as const; return <><DocHead eyebrow="Operations" title="API capability status">Product classification without fabricated uptime statistics.</DocHead><table><thead><tr><th>Capability</th><th>Status</th><th>Notes</th></tr></thead><tbody>{rows.map(([name,status,note]) => <tr key={name}><td>{name}</td><td><StatusBadge value={status} /></td><td>{note}</td></tr>)}</tbody></table></>; }

function SearchDialog({ close }: { close: () => void }) { const [query, setQuery] = useState(""); const results = useMemo(() => { const term = query.trim().toLowerCase(); if (!term) return endpoints.slice(0, 8); return endpoints.filter((item) => `${item.title} ${item.path} ${item.scope} ${item.description} ${item.events?.join(" ")}`.toLowerCase().includes(term)).slice(0, 12); }, [query]); useEffect(() => { const onKey = (event: KeyboardEvent) => event.key === "Escape" && close(); window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [close]); return <div className="search-overlay" role="dialog" aria-modal="true"><button className="search-backdrop" onClick={close} aria-label="Close search" /><div className="search-dialog"><label><Search size={19} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search endpoints, scopes, streams..." /><kbd>Esc</kbd></label><div className="search-results">{results.map((item) => <Link key={item.id} to={`/reference/${item.id}`} onClick={close}><span className={`method ${item.method.toLowerCase()}`}>{item.method}</span><span><strong>{item.title}</strong><small>{item.path}</small></span><ChevronRight size={16} /></Link>)}{query && results.length === 0 && <p>No matching documentation found.</p>}</div></div></div>; }
function OnPageToc({ path }: { path: string }) { const items = path.startsWith("/reference/") ? [["Parameters", "parameters"], ["Request", "request"], ["Example", "example"], ["Response", "response"], ["Events", "events"]] : [["Details", "architecture"], ["Next steps", "next"]]; return <aside className="toc"><strong>On this page</strong>{items.map(([label,id]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>; }
function CodeSample({ title, code }: { title: string; code: string }) { const [copied, setCopied] = useState(false); return <figure className="code-sample"><figcaption><span>{title}</span><button onClick={() => { void navigator.clipboard.writeText(code); setCopied(true); setTimeout(() => setCopied(false), 1200); }}>{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? "Copied" : "Copy"}</button></figcaption><pre><code>{code}</code></pre></figure>; }
function CodeTabs({ samples }: { samples: Record<string, string> }) { const keys = Object.keys(samples); const [active, setActive] = useState(keys[0]); return <div className="code-tabs"><div role="tablist">{keys.map((key) => <button role="tab" aria-selected={key === active} onClick={() => setActive(key)} key={key}>{key}</button>)}</div><CodeSample title={active} code={samples[active]} /></div>; }
function StatusBadge({ value, label }: { value: "STABLE" | "BETA" | "RESTRICTED" | "DEPRECATED"; label?: string }) { return <span className={`status ${value.toLowerCase()}`}>{label || value}</span>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function Callout({ children, tone = "info" }: { children: ReactNode; tone?: "info" | "warning" }) { return <aside className={`callout ${tone}`}><CircleAlert size={18} /><div>{children}</div></aside>; }
function Flow({ items }: { items: string[] }) { return <div className="flow">{items.map((item, index) => <div key={item}><span>{index + 1}</span><strong>{item}</strong>{index < items.length - 1 && <ChevronRight size={16} />}</div>)}</div>; }
function Steps({ items }: { items: string[] }) { return <ol className="steps">{items.map((item) => <li key={item}>{item}</li>)}</ol>; }
function Feature({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) { return <article className="feature">{icon}<h2>{title}</h2><p>{children}</p></article>; }
function TrySandbox({ endpoint }: { endpoint: Endpoint }) {
  type Property = { type?: string; enum?: readonly string[]; format?: string; minimum?: number; maximum?: number; minLength?: number; maxLength?: number; description?: string };
  type Contract = { schema: string; required?: readonly string[]; properties?: Record<string, Property>; example?: Record<string, unknown>; additionalProperties?: boolean };
  const contract = (requestContracts as unknown as Record<string, Contract>)[`${endpoint.method} ${endpoint.path}`];
  const [projectId, setProjectId] = useState(""); const [keyId, setKeyId] = useState("");
  const [body, setBody] = useState(endpoint.body || (contract?.example ? JSON.stringify(contract.example, null, 2) : "{}")); const [result, setResult] = useState<unknown>();
  const [pathValues, setPathValues] = useState<Record<string, string>>({});
  const [running, setRunning] = useState(false); const [failure, setFailure] = useState("");
  useEffect(() => { setBody(endpoint.body || (contract?.example ? JSON.stringify(contract.example, null, 2) : "{}")); setPathValues({}); }, [endpoint.id]);
  const parsedBody = () => JSON.parse(body) as Record<string, unknown>;
  const updateField = (name: string, value: unknown) => { const next = parsedBody(); if (value === "") delete next[name]; else next[name] = value; setBody(JSON.stringify(next, null, 2)); };
  const validateBody = (value: Record<string, unknown>) => {
    if (!contract) return;
    for (const name of contract.required || []) if (value[name] === undefined || value[name] === "") throw new Error(`${name} is required by ${contract.schema}.`);
    if (contract.additionalProperties === false) for (const name of Object.keys(value)) if (!contract.properties?.[name]) throw new Error(`${name} is not accepted by ${contract.schema}.`);
    for (const [name, property] of Object.entries(contract.properties || {})) { const field = value[name]; if (field === undefined) continue; if (property.enum && !property.enum.includes(String(field))) throw new Error(`${name} must be one of: ${property.enum.join(", ")}.`); if (property.type === "integer" && !Number.isInteger(field)) throw new Error(`${name} must be an integer.`); if (property.type === "boolean" && typeof field !== "boolean") throw new Error(`${name} must be true or false.`); if (property.type === "array" && !Array.isArray(field)) throw new Error(`${name} must be a JSON array.`); if (property.type === "object" && (typeof field !== "object" || field === null || Array.isArray(field))) throw new Error(`${name} must be a JSON object.`); if (property.type === "string" && typeof field !== "string") throw new Error(`${name} must be a string.`); }
  };
  const execute = async () => {
    setRunning(true); setFailure(""); setResult(undefined);
    try {
      const path = endpoint.path.replace(/\{([^}]+)\}/g, (_, name: string) => { const value = pathValues[name]; if (!value) throw new Error(`${name} is required.`); return encodeURIComponent(value); });
      const requestBody = contract ? parsedBody() : undefined; if (requestBody) validateBody(requestBody);
      const response = endpoint.auth === "Public"
        ? await fetch(`${apiBaseUrl}${path}`, { headers: { Accept: "application/json" } })
        : await fetch(`${apiBaseUrl}/api/developer/projects/${encodeURIComponent(projectId)}/sandbox/explorer`, {
            method: "POST", credentials: "include", headers: { "Content-Type": "application/json", Accept: "application/json" },
            body: JSON.stringify({ api_key_id: Number(keyId), method: endpoint.method, path, body: requestBody }),
          });
      const payload = await response.json(); setResult(payload);
      if (!response.ok) setFailure(`Request failed with HTTP ${response.status}.`);
    } catch (error) { setFailure(error instanceof Error ? error.message : "Sandbox request failed."); }
    finally { setRunning(false); }
  };
  const bodyValue = (() => { try { return parsedBody(); } catch { return {}; } })();
  const pathNames = Array.from(endpoint.path.matchAll(/\{([^}]+)\}/g), (match) => match[1]);
  return <section className="try-sandbox"><div className="explorer-head"><div><p className="eyebrow">Request console</p><h2>Try in Sandbox</h2><p>Real sandbox request. Private credentials stay encrypted server-side and all returned authentication headers are redacted.</p></div><span className="sandbox-label">SANDBOX · NO REAL FUNDS</span></div>{endpoint.auth === "Signed" && <div className="explorer-fields"><label>Sandbox project ID<input inputMode="numeric" value={projectId} onChange={(event) => setProjectId(event.target.value)} placeholder="Project ID" /></label><label>Explorer API key ID<input inputMode="numeric" value={keyId} onChange={(event) => setKeyId(event.target.value)} placeholder="Key ID" /></label></div>}{pathNames.length > 0 && <div className="explorer-fields">{pathNames.map((name) => <label key={name}>{name}<input value={pathValues[name] || ""} required onChange={(event) => setPathValues((current) => ({ ...current, [name]: event.target.value }))} /></label>)}</div>}{contract?.properties && <div className="schema-fields">{Object.entries(contract.properties).map(([name, property]) => <label key={name}><span>{name}{contract.required?.includes(name) && <strong> Required</strong>}</span>{property.enum ? <select value={String(bodyValue[name] ?? "")} onChange={(event) => updateField(name, event.target.value)}><option value="">Select</option>{property.enum.map((item) => <option key={item} value={item}>{item}</option>)}</select> : property.type === "boolean" ? <input type="checkbox" checked={Boolean(bodyValue[name])} onChange={(event) => updateField(name, event.target.checked)} /> : <input value={typeof bodyValue[name] === "object" ? JSON.stringify(bodyValue[name]) : String(bodyValue[name] ?? "")} inputMode={property.type === "integer" ? "numeric" : undefined} onChange={(event) => { let value: unknown = event.target.value; if (property.type === "integer" && event.target.value) value = Number(event.target.value); if ((property.type === "array" || property.type === "object") && event.target.value) { try { value = JSON.parse(event.target.value); } catch { value = event.target.value; } } updateField(name, value); }} />}</label>)}</div>}{contract && <details className="raw-json"><summary>Advanced JSON editor</summary><label className="explorer-body">Request body<textarea spellCheck={false} value={body} onChange={(event) => setBody(event.target.value)} /></label></details>}<div className="explorer-actions"><button onClick={execute} disabled={running || (endpoint.auth === "Signed" && (!projectId || !keyId))}>{running ? "Sending..." : `Send ${endpoint.method} request`}</button><small>{endpoint.auth === "Signed" ? "Requires an authenticated Developer Console session and a newly generated sandbox key." : "No credentials required."}</small></div>{failure && <p className="explorer-error">{failure}</p>}{result !== undefined && <CodeSample title="Sandbox response" code={JSON.stringify(result, null, 2)} />}</section>;
}
function NotFound() { return <><DocHead eyebrow="404" title="Documentation not found">The requested reference page does not exist in the current API contract.</DocHead><Link to="/docs" className="primary">Back to documentation</Link></>; }

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
