// Generated by scripts/generate-developer-openapi.php. Do not edit manually.
export const requestContracts = {
    "POST /api/developer/projects/{projectId}/production-access": {
        "schema": "ProductionAccessRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "use_case",
            "capabilities",
            "idempotency_key"
        ],
        "properties": {
            "use_case": {
                "type": "string",
                "enum": [
                    "trading_application",
                    "trading_bot",
                    "portfolio_application",
                    "market_data_service",
                    "payment_integration",
                    "wallet_integration",
                    "institutional_integration",
                    "fintech_application",
                    "internal_company_integration",
                    "other"
                ]
            },
            "capabilities": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "string"
                }
            },
            "idempotency_key": {
                "type": "string",
                "maxLength": 100
            },
            "expected_request_volume": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "expected_trading_volume": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "website": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "uri"
            },
            "technical_contact": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "email"
            },
            "business_context": {
                "type": [
                    "string",
                    "null"
                ],
                "maxLength": 2000
            }
        },
        "example": {
            "use_case": "trading_application",
            "capabilities": [
                "account.read",
                "spot.read"
            ],
            "idempotency_key": "prod-access-demo-001"
        }
    },
    "POST /api/developer/v1/convert/execute": {
        "schema": "ConvertExecuteRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "quote_id"
        ],
        "properties": {
            "quote_id": {
                "type": "string",
                "format": "uuid"
            }
        },
        "example": {
            "quote_id": "018f4fd8-4f0a-7d42-9a50-23de9f6c30d2"
        }
    },
    "POST /api/developer/v1/convert/quote": {
        "schema": "ConvertQuoteRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "from_currency",
            "to_currency",
            "amount"
        ],
        "properties": {
            "from_currency": {
                "type": "string",
                "maxLength": 16
            },
            "to_currency": {
                "type": "string",
                "maxLength": 16
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            }
        },
        "example": {
            "from_currency": "USDT",
            "to_currency": "BTC",
            "amount": "100.00000000"
        }
    },
    "POST /api/developer/v1/copy/follow": {
        "schema": "CopyFollowRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "trader_id",
            "amount_allocated"
        ],
        "properties": {
            "trader_id": {
                "type": "integer",
                "minimum": 1
            },
            "amount_allocated": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "risk_level": {
                "type": "string",
                "enum": [
                    "low",
                    "medium",
                    "high"
                ]
            },
            "product_scope": {
                "type": "string",
                "enum": [
                    "spot",
                    "futures",
                    "all"
                ]
            },
            "copy_mode": {
                "type": "string",
                "enum": [
                    "fixed_amount",
                    "proportional",
                    "fixed_ratio"
                ]
            },
            "fixed_amount_per_trade": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "fixed_ratio": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_amount_per_trade": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_daily_loss": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_drawdown": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_leverage": {
                "type": "integer",
                "minimum": 1,
                "maximum": 125
            },
            "margin_preference": {
                "type": "string",
                "enum": [
                    "isolated",
                    "cross",
                    "follow_lead"
                ]
            },
            "allowed_symbols": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "country": {
                "type": "string",
                "minLength": 2,
                "maxLength": 2
            }
        },
        "example": {
            "trader_id": 12,
            "amount_allocated": "250.00000000",
            "risk_level": "medium",
            "product_scope": "spot"
        }
    },
    "PATCH /api/developer/v1/copy/follow/{id}": {
        "schema": "CopyFollowUpdateRequest",
        "type": "object",
        "additionalProperties": false,
        "minProperties": 1,
        "properties": {
            "max_amount_per_trade": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_daily_loss": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_drawdown": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_leverage": {
                "type": "integer",
                "minimum": 1,
                "maximum": 125
            },
            "allowed_symbols": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "status": {
                "type": "string",
                "enum": [
                    "active",
                    "paused"
                ]
            }
        },
        "example": {
            "max_amount_per_trade": "50.00000000",
            "status": "active"
        }
    },
    "DELETE /api/developer/v1/copy/follow/{id}": {
        "schema": "CopyStopRequest",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "action": {
                "type": "string",
                "enum": [
                    "STOP_NEW_TRADES",
                    "STOP_AND_CLOSE_COPIED_POSITIONS",
                    "DETACH_POSITION"
                ]
            },
            "reason": {
                "type": "string",
                "maxLength": 500
            }
        },
        "example": {
            "action": "STOP_NEW_TRADES",
            "reason": "Sandbox lifecycle test"
        }
    },
    "POST /api/developer/v1/copy/terms/accept": {
        "schema": "CopyTermsRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "types"
        ],
        "properties": {
            "types": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                    "type": "string",
                    "enum": [
                        "copy_trading_terms",
                        "risk_disclosure",
                        "futures_copy_disclosure",
                        "profit_share_terms"
                    ]
                }
            }
        },
        "example": {
            "types": [
                "copy_trading_terms",
                "risk_disclosure"
            ]
        }
    },
    "POST /api/developer/v1/exaai/allocations": {
        "schema": "ExaAiAllocationRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "asset",
            "amount"
        ],
        "properties": {
            "asset": {
                "type": "string",
                "maxLength": 20
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            }
        },
        "example": {
            "asset": "USDT",
            "amount": "500.00000000"
        }
    },
    "POST /api/developer/v1/exaai/sessions": {
        "schema": "ExaAiSessionRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "allocation_id",
            "strategy_id"
        ],
        "properties": {
            "allocation_id": {
                "type": "integer",
                "minimum": 1
            },
            "strategy_id": {
                "type": "integer",
                "minimum": 1
            },
            "mode": {
                "type": "string",
                "enum": [
                    "paper",
                    "shadow",
                    "live",
                    "demo"
                ]
            },
            "live_authorization": {
                "type": "boolean"
            },
            "duration": {
                "type": "string",
                "enum": [
                    "24h",
                    "7d",
                    "30d",
                    "90d",
                    "manual"
                ]
            },
            "max_daily_loss": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_drawdown_percent": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "max_open_positions": {
                "type": "integer",
                "minimum": 1,
                "maximum": 100
            },
            "eligible_markets": {
                "type": "array",
                "items": {
                    "type": "string",
                    "maxLength": 40
                }
            },
            "constraints": {
                "type": "object",
                "additionalProperties": true,
                "description": "Strategy-defined non-financial constraint map validated by ExaAI governance."
            }
        },
        "example": {
            "allocation_id": 10,
            "strategy_id": 3,
            "mode": "shadow",
            "duration": "7d",
            "max_daily_loss": "25.00000000"
        }
    },
    "POST /api/developer/v1/exaai/terms/accept": {
        "schema": "ExaAiTermsRequest",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "terms_version": {
                "type": "string",
                "maxLength": 40
            }
        },
        "example": {
            "terms_version": "phase13-v1"
        }
    },
    "POST /api/developer/v1/exapay/merchants/{merchantId}/payment-intents": {
        "schema": "ExaPayIntentRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "amount",
            "currency",
            "idempotency_key"
        ],
        "properties": {
            "payer_user_id": {
                "type": "integer",
                "minimum": 1
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "currency": {
                "type": "string",
                "maxLength": 8
            },
            "description": {
                "type": "string",
                "maxLength": 200
            },
            "merchant_reference": {
                "type": "string",
                "maxLength": 160
            },
            "customer_reference": {
                "type": "string",
                "maxLength": 160
            },
            "environment": {
                "type": "string",
                "enum": [
                    "SANDBOX",
                    "PRODUCTION",
                    "sandbox",
                    "production"
                ]
            },
            "capture_mode": {
                "type": "string",
                "enum": [
                    "AUTOMATIC",
                    "MANUAL",
                    "automatic",
                    "manual"
                ]
            },
            "payment_method": {
                "type": "string",
                "maxLength": 40
            },
            "idempotency_key": {
                "type": "string",
                "maxLength": 160
            },
            "expires_at": {
                "type": "string",
                "format": "date-time"
            },
            "metadata": {
                "type": "object",
                "additionalProperties": true
            }
        },
        "example": {
            "amount": "25.00000000",
            "currency": "USDT",
            "environment": "sandbox",
            "capture_mode": "AUTOMATIC",
            "idempotency_key": "sandbox-pay-001"
        }
    },
    "POST /api/developer/v1/exapay/merchants/{merchantId}/payment-links": {
        "schema": "ExaPayLinkRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "title"
        ],
        "properties": {
            "title": {
                "type": "string",
                "maxLength": 160
            },
            "description": {
                "type": "string",
                "maxLength": 500
            },
            "amount_mode": {
                "type": "string",
                "enum": [
                    "FIXED",
                    "VARIABLE",
                    "fixed",
                    "variable"
                ]
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "currency": {
                "type": "string",
                "maxLength": 8
            },
            "maximum_uses": {
                "type": "integer",
                "minimum": 1
            },
            "success_url": {
                "type": "string",
                "format": "uri",
                "maxLength": 255
            },
            "cancel_url": {
                "type": "string",
                "format": "uri",
                "maxLength": 255
            },
            "expires_at": {
                "type": "string",
                "format": "date-time"
            },
            "customer_fields": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "example": {
            "title": "Sandbox invoice",
            "amount_mode": "FIXED",
            "amount": "25.00000000",
            "currency": "USDT"
        }
    },
    "POST /api/developer/v1/exapay/merchants/{merchantId}/refunds": {
        "schema": "ExaPayRefundRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "payment_reference",
            "currency",
            "reason"
        ],
        "properties": {
            "payment_reference": {
                "type": "string",
                "maxLength": 160
            },
            "currency": {
                "type": "string",
                "maxLength": 8
            },
            "reason": {
                "type": "string",
                "maxLength": 160
            }
        },
        "example": {
            "payment_reference": "PAY-SANDBOX-001",
            "currency": "USDT",
            "reason": "Sandbox customer request"
        }
    },
    "POST /api/developer/v1/futures/margin/type": {
        "schema": "FuturesMarginTypeRequest",
        "type": "object",
        "required": [
            "position_id",
            "margin_type"
        ],
        "properties": {
            "position_id": {
                "type": "integer"
            },
            "margin_type": {
                "type": "string",
                "enum": [
                    "cross",
                    "isolated"
                ]
            }
        },
        "example": {
            "position_id": 10,
            "margin_type": "isolated"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/futures/orders": {
        "schema": "FuturesOrderRequest",
        "type": "object",
        "required": [
            "symbol",
            "type",
            "side",
            "quantity",
            "leverage"
        ],
        "properties": {
            "symbol": {
                "type": "string",
                "maxLength": 32
            },
            "type": {
                "type": "string",
                "enum": [
                    "market",
                    "limit",
                    "stop-market",
                    "stop-limit",
                    "trailing-stop"
                ]
            },
            "side": {
                "type": "string",
                "enum": [
                    "long",
                    "short"
                ]
            },
            "quantity": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "stop_price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "leverage": {
                "type": "integer",
                "minimum": 1,
                "maximum": 100
            },
            "reduce_only": {
                "type": "boolean"
            },
            "post_only": {
                "type": "boolean"
            },
            "time_in_force": {
                "type": "string",
                "enum": [
                    "GTC",
                    "IOC",
                    "FOK"
                ]
            },
            "client_order_id": {
                "type": "string",
                "maxLength": 80
            },
            "trigger_source": {
                "type": "string",
                "enum": [
                    "MARK",
                    "LAST",
                    "INDEX",
                    "mark",
                    "last",
                    "index"
                ]
            },
            "trailing_distance": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "metadata": {
                "type": "object",
                "additionalProperties": true
            }
        },
        "example": {
            "symbol": "BTC-USDT",
            "type": "limit",
            "side": "long",
            "quantity": "0.00100000",
            "price": "65000.00000000",
            "leverage": 2
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/futures/orders/batch-cancel": {
        "schema": "BatchCancelRequest",
        "type": "object",
        "required": [
            "order_uuids"
        ],
        "properties": {
            "order_uuids": {
                "type": "array",
                "minItems": 1,
                "maxItems": 50,
                "items": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "example": {
            "order_uuids": [
                "018f4fd8-4f0a-7d42-9a50-23de9f6c30d2"
            ]
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/futures/orders/conditional": {
        "schema": "FuturesConditionalOrderRequest",
        "type": "object",
        "required": [
            "symbol",
            "type",
            "trigger_order_type",
            "trigger_price",
            "quantity"
        ],
        "properties": {
            "symbol": {
                "type": "string"
            },
            "type": {
                "type": "string",
                "enum": [
                    "stop_loss",
                    "take_profit"
                ]
            },
            "trigger_order_type": {
                "type": "string",
                "enum": [
                    "market",
                    "limit"
                ]
            },
            "trigger_price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "execution_price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "quantity": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "position_id": {
                "type": "integer",
                "minimum": 1
            },
            "metadata": {
                "type": "object",
                "additionalProperties": true
            }
        },
        "example": {
            "symbol": "BTC-USDT",
            "type": "stop_loss",
            "trigger_order_type": "market",
            "trigger_price": "62000.00000000",
            "quantity": "0.00100000"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/futures/orders/validate": {
        "schema": "FuturesOrderRequest",
        "type": "object",
        "required": [
            "symbol",
            "type",
            "side",
            "quantity",
            "leverage"
        ],
        "properties": {
            "symbol": {
                "type": "string",
                "maxLength": 32
            },
            "type": {
                "type": "string",
                "enum": [
                    "market",
                    "limit",
                    "stop-market",
                    "stop-limit",
                    "trailing-stop"
                ]
            },
            "side": {
                "type": "string",
                "enum": [
                    "long",
                    "short"
                ]
            },
            "quantity": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "stop_price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "leverage": {
                "type": "integer",
                "minimum": 1,
                "maximum": 100
            },
            "reduce_only": {
                "type": "boolean"
            },
            "post_only": {
                "type": "boolean"
            },
            "time_in_force": {
                "type": "string",
                "enum": [
                    "GTC",
                    "IOC",
                    "FOK"
                ]
            },
            "client_order_id": {
                "type": "string",
                "maxLength": 80
            },
            "trigger_source": {
                "type": "string",
                "enum": [
                    "MARK",
                    "LAST",
                    "INDEX",
                    "mark",
                    "last",
                    "index"
                ]
            },
            "trailing_distance": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "metadata": {
                "type": "object",
                "additionalProperties": true
            }
        },
        "example": {
            "symbol": "BTC-USDT",
            "type": "limit",
            "side": "long",
            "quantity": "0.00100000",
            "price": "65000.00000000",
            "leverage": 2
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/margin/accounts": {
        "schema": "MarginAccountRequest",
        "type": "object",
        "required": [
            "mode"
        ],
        "properties": {
            "mode": {
                "type": "string",
                "enum": [
                    "CROSS",
                    "ISOLATED"
                ]
            },
            "market_symbol": {
                "type": "string"
            }
        },
        "example": {
            "mode": "ISOLATED",
            "market_symbol": "BTC/USDT"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/margin/borrow": {
        "schema": "MarginBorrowRequest",
        "type": "object",
        "required": [
            "account_uuid",
            "asset",
            "amount"
        ],
        "properties": {
            "account_uuid": {
                "type": "string"
            },
            "asset": {
                "type": "string"
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "idempotency_key": {
                "type": "string",
                "maxLength": 120
            }
        },
        "example": {
            "account_uuid": "margin-sandbox-001",
            "asset": "USDT",
            "amount": "50.00000000",
            "idempotency_key": "sandbox-margin-borrow-001"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/margin/loans/{loanUuid}/repay": {
        "schema": "MarginRepayRequest",
        "type": "object",
        "required": [
            "amount"
        ],
        "properties": {
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "idempotency_key": {
                "type": "string",
                "maxLength": 120
            }
        },
        "example": {
            "amount": "10.00000000",
            "idempotency_key": "sandbox-margin-repay-001"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/margin/orders": {
        "schema": "MarginOrderRequest",
        "type": "object",
        "required": [
            "account_uuid",
            "client_order_id",
            "pair",
            "side",
            "type",
            "amount"
        ],
        "properties": {
            "account_uuid": {
                "type": "string"
            },
            "client_order_id": {
                "type": "string"
            },
            "pair": {
                "type": "string"
            },
            "side": {
                "type": "string",
                "enum": [
                    "buy",
                    "sell"
                ]
            },
            "type": {
                "type": "string",
                "enum": [
                    "limit",
                    "market"
                ]
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "borrow_mode": {
                "type": "string",
                "enum": [
                    "NORMAL",
                    "AUTO_BORROW",
                    "AUTO_REPAY"
                ]
            },
            "time_in_force": {
                "type": "string",
                "enum": [
                    "GTC",
                    "IOC",
                    "FOK",
                    "gtc",
                    "ioc",
                    "fok"
                ]
            },
            "post_only": {
                "type": "boolean"
            }
        },
        "example": {
            "account_uuid": "margin-sandbox-001",
            "client_order_id": "sandbox-margin-order-001",
            "pair": "BTC/USDT",
            "side": "buy",
            "type": "limit",
            "amount": "0.00100000",
            "price": "65000.00000000"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/margin/transfer": {
        "schema": "MarginTransferRequest",
        "type": "object",
        "required": [
            "account_uuid",
            "direction",
            "asset",
            "amount"
        ],
        "properties": {
            "account_uuid": {
                "type": "string"
            },
            "direction": {
                "type": "string",
                "enum": [
                    "IN",
                    "OUT"
                ]
            },
            "asset": {
                "type": "string"
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "idempotency_key": {
                "type": "string",
                "maxLength": 120
            },
            "source_account": {
                "type": "string",
                "maxLength": 64
            },
            "destination_account": {
                "type": "string",
                "maxLength": 64
            }
        },
        "example": {
            "account_uuid": "margin-sandbox-001",
            "direction": "IN",
            "asset": "USDT",
            "amount": "100.00000000",
            "idempotency_key": "sandbox-margin-transfer-001"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/realtime/session": {
        "schema": "RealtimeSessionRequest",
        "type": "object",
        "required": [
            "topics"
        ],
        "properties": {
            "topics": {
                "type": "array",
                "minItems": 1,
                "maxItems": 100,
                "items": {
                    "type": "string"
                }
            }
        },
        "example": {
            "topics": [
                "account.balance",
                "order"
            ]
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/spot/orders": {
        "schema": "SpotOrderRequest",
        "type": "object",
        "required": [
            "symbol",
            "side",
            "type",
            "quantity"
        ],
        "properties": {
            "symbol": {
                "type": "string"
            },
            "side": {
                "type": "string",
                "enum": [
                    "buy",
                    "sell"
                ]
            },
            "type": {
                "type": "string",
                "enum": [
                    "market",
                    "limit",
                    "stop_loss",
                    "take_profit"
                ]
            },
            "quantity": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "price": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "client_order_id": {
                "type": "string",
                "maxLength": 80
            }
        },
        "example": {
            "symbol": "BTC-USDT",
            "side": "buy",
            "type": "limit",
            "quantity": "0.00100000",
            "price": "65000.00000000",
            "client_order_id": "sandbox-spot-001"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/staking/positions": {
        "schema": "StakingPositionRequest",
        "type": "object",
        "required": [
            "staking_product_id",
            "amount",
            "terms_version",
            "idempotency_key"
        ],
        "properties": {
            "staking_product_id": {
                "type": "integer"
            },
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "auto_compound": {
                "type": "boolean"
            },
            "terms_version": {
                "type": "string"
            },
            "idempotency_key": {
                "type": "string"
            },
            "transaction_pin": {
                "type": "string",
                "maxLength": 120
            },
            "two_factor_code": {
                "type": "string",
                "maxLength": 20
            }
        },
        "example": {
            "staking_product_id": 1,
            "amount": "100.00000000",
            "terms_version": "staking-v1",
            "idempotency_key": "sandbox-stake-001"
        },
        "additionalProperties": false
    },
    "PATCH /api/developer/v1/staking/positions/{publicId}/auto-compound": {
        "schema": "StakingAutoCompoundRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "auto_compound"
        ],
        "properties": {
            "auto_compound": {
                "type": "boolean"
            }
        },
        "example": {
            "auto_compound": true
        }
    },
    "POST /api/developer/v1/staking/positions/{publicId}/unstake": {
        "schema": "StakingUnstakeRequest",
        "type": "object",
        "required": [
            "idempotency_key"
        ],
        "properties": {
            "amount": {
                "type": "string",
                "pattern": "^-?[0-9]+(?:\\.[0-9]+)?$",
                "example": "100.00000000"
            },
            "idempotency_key": {
                "type": "string"
            },
            "transaction_pin": {
                "type": "string",
                "maxLength": 120
            },
            "two_factor_code": {
                "type": "string",
                "maxLength": 20
            }
        },
        "example": {
            "amount": "25.00000000",
            "idempotency_key": "sandbox-unstake-001"
        },
        "additionalProperties": false
    },
    "POST /api/developer/v1/staking/terms/accept": {
        "schema": "TermsAcceptanceRequest",
        "type": "object",
        "additionalProperties": false,
        "required": [
            "terms_version"
        ],
        "properties": {
            "terms_version": {
                "type": "string",
                "maxLength": 32
            }
        },
        "example": {
            "terms_version": "staking-v1"
        }
    }
} as const;
