import { useEffect, useState } from "react";
import { Archive, Copy, Eye, Pause, Play, Plus, X } from "lucide-react";
import { GlassPanel, PageShell, Pill } from "../components/AdminPrimitives";
import { adminHttp } from "../services/http";

const EMPTY = { type: "CAMPAIGN", title: "", subtitle: "", body: "", badge: "", cta_label: "View Details", cta_route: "campaigns", related_product: "", related_asset: "", priority: 50, frequency_cap: 5, minimum_kyc_tier: 0, target_interests: "", target_countries: "", target_experience_modes: ["LITE", "PRO"], publish_at: "", expires_at: "", status: "DRAFT" };
const TYPES = ["CAMPAIGN", "PLATFORM_UPDATE", "MARKET_NEWS", "MARKET_INSIGHT", "EXAAI_INSIGHT", "EARN_OPPORTUNITY", "CROWDFUNDING_UPDATE", "PRODUCT_LAUNCH", "EDUCATION", "REWARD", "PROMOTION", "SECURITY_INFORMATION", "MAINTENANCE", "ECOSYSTEM_DISCOVERY"];
const ROUTES = ["trade", "market", "futures", "swap", "p2pMarketplace", "aiAssistant", "staking", "crowdfunding", "agriculture", "edtech", "exacard", "nftMarketplace", "game", "giftcard", "rewards", "campaigns", "settings"];

export function ContentManagerPage() {
  const [items, setItems] = useState([]); const [editing, setEditing] = useState(null); const [form, setForm] = useState(EMPTY); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const { data } = await adminHttp.get("/personalized-content"); setItems(data?.data?.data || []); setError(""); } catch (exception) { setError(exception.response?.data?.message || "Content manager is unavailable."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const payload = () => ({ ...form, target_interests: form.target_interests.split(",").map((v) => v.trim()).filter(Boolean), target_countries: form.target_countries.split(",").map((v) => v.trim().toUpperCase()).filter(Boolean), related_product: form.related_product || null, related_asset: form.related_asset || null, publish_at: form.publish_at || null, expires_at: form.expires_at || null });
  const save = async () => { try { if (editing) await adminHttp.patch(`/personalized-content/${editing.id}`, payload()); else await adminHttp.post("/personalized-content", payload()); setEditing(null); setForm(EMPTY); await load(); } catch (exception) { setError(exception.response?.data?.message || "Could not save content."); } };
  const transition = async (item, action) => { await adminHttp.post(`/personalized-content/${item.id}/${action}`); await load(); };
  const edit = (item) => { setEditing(item); setForm({ ...EMPTY, ...item, target_interests: (item.target_interests || []).join(", "), target_countries: (item.target_countries || []).join(", "), publish_at: item.publish_at?.slice(0, 16) || "", expires_at: item.expires_at?.slice(0, 16) || "" }); };

  return <PageShell eyebrow="Content intelligence" title="Campaign & Content Manager" description="Create, schedule, target, publish and measure normalized ExaEarn discovery content.">
    {error ? <div className="mb-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-100">{error}</div> : null}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
      <GlassPanel><div className="flex items-center justify-between"><h2 className="font-['Sora'] text-lg font-semibold">Content</h2><button type="button" onClick={() => { setEditing(null); setForm(EMPTY); }} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-auric-300 px-3 text-sm font-semibold text-cosmic-950"><Plus className="h-4 w-4"/>New</button></div>
        <div className="mt-4 grid gap-3">{loading ? <p className="text-sm text-violet-100/60">Loading content...</p> : items.map((item) => <article key={item.id} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex gap-2"><Pill>{item.type}</Pill><Pill tone={item.status === "PUBLISHED" ? "success" : "warning"}>{item.status}</Pill></div><h3 className="mt-3 font-semibold text-white">{item.title}</h3><p className="mt-1 text-xs text-violet-100/60">{item.body || item.subtitle}</p></div><button type="button" onClick={() => edit(item)} className="min-h-10 px-3 text-xs text-auric-200">Edit</button></div><div className="mt-3 flex flex-wrap items-center gap-2 text-xs"><span>{item.impressions_count || 0} impressions</span><span>{item.clicks_count || 0} clicks</span><span>{item.dismissals_count || 0} dismissals</span><div className="ml-auto flex"><button type="button" onClick={() => transition(item, item.status === "PUBLISHED" ? "pause" : "publish")} className="grid h-10 w-10 place-items-center" title={item.status === "PUBLISHED" ? "Pause" : "Publish"}>{item.status === "PUBLISHED" ? <Pause/> : <Play/>}</button><button type="button" onClick={() => transition(item, "duplicate")} className="grid h-10 w-10 place-items-center" title="Duplicate"><Copy/></button><button type="button" onClick={() => transition(item, "archive")} className="grid h-10 w-10 place-items-center" title="Archive"><Archive/></button></div></div></article>)}</div>
      </GlassPanel>
      <GlassPanel><div className="flex justify-between"><h2 className="font-['Sora'] text-lg font-semibold">{editing ? "Edit content" : "Create content"}</h2>{editing ? <button type="button" onClick={() => { setEditing(null); setForm(EMPTY); }}><X/></button> : null}</div><div className="mt-4 grid gap-3">
        <Field label="Type"><select value={form.type} onChange={(e) => change("type", e.target.value)}>{TYPES.map((v) => <option key={v}>{v}</option>)}</select></Field><Field label="Title"><input value={form.title} maxLength={160} onChange={(e) => change("title", e.target.value)} /></Field><Field label="Subtitle"><input value={form.subtitle || ""} onChange={(e) => change("subtitle", e.target.value)} /></Field><Field label="Description"><textarea rows="3" value={form.body || ""} onChange={(e) => change("body", e.target.value)} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Badge"><input value={form.badge || ""} onChange={(e) => change("badge", e.target.value)} /></Field><Field label="CTA"><input value={form.cta_label || ""} onChange={(e) => change("cta_label", e.target.value)} /></Field></div><Field label="Safe destination"><select value={form.cta_route || ""} onChange={(e) => change("cta_route", e.target.value)}>{ROUTES.map((v) => <option key={v}>{v}</option>)}</select></Field><div className="grid grid-cols-2 gap-2"><Field label="Product"><input value={form.related_product || ""} onChange={(e) => change("related_product", e.target.value.toUpperCase())} /></Field><Field label="Asset"><input value={form.related_asset || ""} onChange={(e) => change("related_asset", e.target.value.toUpperCase())} /></Field></div><Field label="Interests (comma separated)"><input value={form.target_interests} onChange={(e) => change("target_interests", e.target.value)} /></Field><Field label="Countries (ISO, comma separated)"><input value={form.target_countries} onChange={(e) => change("target_countries", e.target.value)} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Publish at"><input type="datetime-local" value={form.publish_at} onChange={(e) => change("publish_at", e.target.value)} /></Field><Field label="Expires at"><input type="datetime-local" value={form.expires_at} onChange={(e) => change("expires_at", e.target.value)} /></Field></div><button type="button" onClick={save} disabled={!form.title} className="min-h-11 rounded-lg bg-auric-300 font-semibold text-cosmic-950 disabled:opacity-40">{editing ? "Save changes" : "Create draft"}</button>
        {form.title ? <div className="rounded-xl border border-cyan-300/20 bg-cyan-300/[.04] p-4"><div className="flex items-center gap-2 text-[10px] font-bold text-cyan-200"><Eye className="h-4 w-4"/>PREVIEW · {form.badge || form.type}</div><strong className="mt-2 block">{form.title}</strong><p className="mt-1 text-xs text-violet-100/60">{form.subtitle || form.body}</p></div> : null}
      </div></GlassPanel>
    </div>
  </PageShell>;
}

function Field({ label, children }) { return <label className="grid gap-1 text-xs text-violet-100/60"><span>{label}</span><span className="[&>*]:w-full [&>*]:rounded-lg [&>*]:border [&>*]:border-white/10 [&>*]:bg-white/5 [&>*]:px-3 [&>*]:py-2.5 [&>*]:text-sm [&>*]:text-white [&>*]:outline-none">{children}</span></label>; }
