import { Ionicons } from "@expo/vector-icons";
import { useEffect, useMemo, useState } from "react";
import { Modal, ScrollView, StyleSheet, Text, View } from "react-native";
import { AnimatedPressable } from "./AnimatedPressable";
import { colors, fonts } from "../theme/colors";

type Key = "crypto_exchange"|"exaai"|"earn"|"giftcards"|"games"|"exaskills"|"crowdfund"|"nft_marketplace"|"agritech";
type Preferences = { mode:"all"|"personalized"; primary_interest:Key|null; selected_interests:Key[]; hidden_widgets:string[]; widget_order:string[]; onboarding_completed:boolean };
const registry: Record<Key,{label:string;description:string;panel:string}> = {
  crypto_exchange:{label:"Crypto Exchange",description:"Markets, conversion, orders, and P2P.",panel:"Trade"}, exaai:{label:"ExaAI",description:"Strategies, allocations, sessions, and performance.",panel:"ExaAI"}, earn:{label:"Earn",description:"Supported staking positions and rewards.",panel:"ExaEarn Staking"}, giftcards:{label:"Gift Cards",description:"Buy, submit, and track card settlement.",panel:"Gift Cards"}, games:{label:"Games",description:"Flight game and recent bet activity.",panel:"Games"}, exaskills:{label:"ExaSkills",description:"Courses, credentials, and challenges.",panel:"ExaSkills"}, crowdfund:{label:"Crowdfund",description:"Discover community campaigns.",panel:"Crowdfund"}, nft_marketplace:{label:"NFT Marketplace",description:"Collections, ownership, and listings.",panel:"NFT Market"}, agritech:{label:"Agritech",description:"Projects and agricultural participation.",panel:"Agritech"},
};
const defaults:Preferences={mode:"all",primary_interest:null,selected_interests:[],hidden_widgets:[],widget_order:[],onboarding_completed:false};
type RequestOptions={method?:string;headers?:Record<string,string>;body?:string};
type Request=<T>(path:string,options?:RequestOptions)=>Promise<T>;

export function DashboardPersonalization({request,onOpenPanel}:{request:Request;onOpenPanel:(panel:string)=>void}) {
  const [preferences,setPreferences]=useState(defaults); const [draft,setDraft]=useState(defaults); const [state,setState]=useState<Record<string,Record<string,number>>>({}); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false);
  useEffect(()=>{request<{data:{preferences:Preferences;state:Record<string,Record<string,number>>}}>("/api/dashboard").then(({data})=>{setPreferences(data.preferences);setDraft(data.preferences);setState(data.state||{});}).catch(()=>undefined);},[request]);
  const experiences=useMemo(()=>preferences.mode==="personalized"?[...preferences.selected_interests].sort((a,b)=>a===preferences.primary_interest?-1:b===preferences.primary_interest?1:0):[],[preferences]);
  const toggle=(key:Key)=>setDraft(current=>{const values=current.selected_interests;const next=values.includes(key)?values.filter(item=>item!==key):values.length<3?[...values,key]:values;return{...current,mode:next.length?"personalized":"all",selected_interests:next,primary_interest:next.includes(current.primary_interest as Key)?current.primary_interest:next[0]||null};});
  const save=async()=>{setBusy(true);try{const result=await request<{data:Preferences}>("/api/preferences/dashboard",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,onboarding_completed:true})});setPreferences(result.data);setOpen(false);}finally{setBusy(false);}};
  const reset=async()=>{setBusy(true);try{await request("/api/preferences/dashboard",{method:"DELETE"});setPreferences(defaults);setDraft(defaults);setOpen(false);}finally{setBusy(false);}};
  return <><View style={s.heading}><View><Text style={s.kicker}>{experiences.length?"FOR YOU":"ALL EXAEARN"}</Text><Text style={s.title}>{experiences.length?"Your Experiences":"Make ExaEarn yours"}</Text></View><AnimatedPressable style={s.customize} onPress={()=>{setDraft(preferences);setOpen(true);}}><Ionicons name="options-outline" size={15} color={colors.auric300}/><Text style={s.customizeText}>Personalize</Text></AnimatedPressable></View>
  {experiences.length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.cards}>{experiences.map(key=>{const item=registry[key];const metric=Object.values(state[key]||{})[0]||0;return <AnimatedPressable key={key} style={[s.card,key===preferences.primary_interest&&s.primary]} onPress={()=>onOpenPanel(item.panel)}><Text style={s.meta}>{key===preferences.primary_interest?"PRIMARY":"SELECTED"}</Text><Text style={s.cardTitle}>{item.label}</Text><Text style={s.body} numberOfLines={2}>{item.description}</Text><Text style={s.metric}>{metric?`${metric} active`:"Explore now"}</Text></AnimatedPressable>;})}</ScrollView>:null}
  <Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={s.backdrop}><View style={s.sheet}><View style={s.sheetHead}><View><Text style={s.kicker}>FOR YOU</Text><Text style={s.sheetTitle}>Personalize dashboard</Text><Text style={s.copy}>Choose up to three. Tap a selected choice to make it primary.</Text></View><AnimatedPressable onPress={()=>setOpen(false)}><Ionicons name="close" size={22} color="#fff"/></AnimatedPressable></View><ScrollView contentContainerStyle={s.options}>{(Object.keys(registry) as Key[]).map(key=>{const selected=draft.selected_interests.includes(key);return <AnimatedPressable key={key} style={[s.option,selected&&s.optionActive]} onPress={()=>selected?setDraft({...draft,primary_interest:key}):toggle(key)}><View style={s.optionTitle}><Text style={s.cardTitle}>{registry[key].label}</Text>{selected?<Ionicons name={draft.primary_interest===key?"star":"checkmark-circle"} size={18} color={colors.auric300}/>:null}</View><Text style={s.body}>{registry[key].description}</Text></AnimatedPressable>;})}</ScrollView><View style={s.actions}><AnimatedPressable style={s.reset} onPress={reset} disabled={busy}><Text style={s.resetText}>Reset</Text></AnimatedPressable><AnimatedPressable style={s.save} onPress={save} disabled={busy}><Text style={s.saveText}>{busy?"Saving…":"Save dashboard"}</Text></AnimatedPressable></View></View></View></Modal></>;
}
const s=StyleSheet.create({heading:{marginTop:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},kicker:{fontFamily:fonts.semibold,fontSize:9,letterSpacing:1.5,color:colors.auric300},title:{marginTop:3,fontFamily:fonts.display,fontSize:15,color:"#fff"},customize:{flexDirection:"row",alignItems:"center",gap:5,borderWidth:1,borderColor:"rgba(212,175,55,.35)",borderRadius:18,paddingHorizontal:10,paddingVertical:7},customizeText:{fontFamily:fonts.semibold,fontSize:10,color:"#f3e8c8"},cards:{gap:8,paddingVertical:10},card:{width:190,minHeight:126,borderWidth:1,borderColor:"#26334a",borderRadius:15,backgroundColor:"#101a2c",padding:12},primary:{borderColor:colors.auric300,backgroundColor:"#241f1b"},meta:{fontFamily:fonts.semibold,fontSize:8,color:colors.auric300},cardTitle:{marginTop:5,fontFamily:fonts.semibold,fontSize:13,color:"#fff"},body:{marginTop:5,fontFamily:fonts.body,fontSize:10,lineHeight:15,color:"#9eabc0"},metric:{marginTop:"auto",fontFamily:fonts.semibold,fontSize:10,color:"#f8e7a1"},backdrop:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(2,6,15,.78)"},sheet:{maxHeight:"90%",borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1,borderColor:"rgba(212,175,55,.3)",backgroundColor:"#0b1220",padding:18},sheetHead:{flexDirection:"row",justifyContent:"space-between",gap:12},sheetTitle:{marginTop:4,fontFamily:fonts.display,fontSize:21,color:"#fff"},copy:{maxWidth:300,marginTop:5,fontFamily:fonts.body,fontSize:11,color:"#9eabc0"},options:{gap:8,paddingVertical:15},option:{borderWidth:1,borderColor:"#26334a",borderRadius:14,backgroundColor:"#101a2c",padding:12},optionActive:{borderColor:colors.auric300},optionTitle:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},actions:{flexDirection:"row",gap:9},reset:{flex:1,alignItems:"center",borderWidth:1,borderColor:"#39475f",borderRadius:12,padding:12},resetText:{fontFamily:fonts.semibold,color:"#c9d2df"},save:{flex:2,alignItems:"center",borderRadius:12,backgroundColor:colors.auric300,padding:12},saveText:{fontFamily:fonts.semibold,color:"#111827"}});
