<?php

declare(strict_types=1);

return [
    'timestamp_tolerance_seconds' => env('DEVELOPER_API_TIMESTAMP_TOLERANCE', 300),
    'max_keys_per_project' => env('DEVELOPER_API_MAX_KEYS_PER_PROJECT', 5),
    'sandbox_faucet' => [
        'USDT' => '10000.00000000',
        'BTC' => '1.00000000',
        'ETH' => '10.00000000',
        'SOL' => '100.00000000',
    ],
    'permissions' => [
        'market.read',
        'account.read',
        'spot.read',
        'spot.trade',
        'futures.read',
        'futures.trade',
        'margin.read',
        'margin.trade',
        'margin.manage',
        'convert.read',
        'convert.execute',
        'wallet.read',
        'wallet.transfer',
        'wallet.withdraw',
        'staking.read',
        'staking.execute',
        'staking.manage',
        'copy.read',
        'copy.execute',
        'copy.manage',
        'p2p.read',
        'p2p.trade',
        'fiat.read',
        'fiat.deposit',
        'fiat.payout',
        'exapay.read',
        'exapay.write',
        'exapay.refunds',
        'exapay.manage',
        'giftcard.read',
        'giftcard.trade',
        'exaai.read',
        'exaai.execute',
        'exaai.manage',
        'webhooks.manage',
    ],
    'rate_limits' => [
        'public_per_minute' => 240,
        'private_per_minute' => 120,
        'trade_per_minute' => 60,
        'withdrawal_per_minute' => 10,
    ],
    'websocket' => [
        'heartbeat_seconds' => 30,
        'max_subscriptions' => 100,
        'queue_limit' => 1000,
        'replay_limit' => 500,
        'allowed_topics' => [
            'market.*',
            'account.balance',
            'order',
            'trade',
            'position',
            'margin',
            'deposit',
            'withdrawal',
            'staking',
            'copy',
            'exaai',
        ],
    ],
    'webhooks' => [
        'timeout_seconds' => 5,
        'max_attempts' => 8,
        'events' => [
            'order.filled',
            'order.cancelled',
            'deposit.completed',
            'withdrawal.completed',
            'withdrawal.failed',
            'transfer.completed',
            'copy.event',
            'exaai.event',
            'payment.created',
            'payment.processing',
            'payment.captured',
            'payment.failed',
            'payment.refunded',
            'payment.partially_refunded',
            'dispute.created',
            'dispute.updated',
            'settlement.created',
            'settlement.completed',
            'settlement.failed',
        ],
    ],
    'api_status' => [
        'spot' => 'AVAILABLE',
        'futures' => 'PRIVATE_BETA',
        'margin' => 'PRIVATE_BETA',
        'convert' => 'AVAILABLE',
        'wallet' => 'AVAILABLE',
        'staking' => 'AVAILABLE',
        'copy' => 'PRIVATE_BETA',
        'exaai' => 'PRIVATE_BETA',
    ],
];
