<?php

declare(strict_types=1);

return [
    'timestamp_tolerance_seconds' => env('DEVELOPER_API_TIMESTAMP_TOLERANCE', 300),
    'runtime_environment' => env('DEVELOPER_API_RUNTIME_ENVIRONMENT', 'sandbox'),
    'max_keys_per_project' => env('DEVELOPER_API_MAX_KEYS_PER_PROJECT', 5),
    'max_personal_projects' => env('DEVELOPER_MAX_PERSONAL_PROJECTS', 5),
    'max_organization_projects' => env('DEVELOPER_MAX_ORGANIZATION_PROJECTS', 20),
    'production_access' => [
        'kyc_max_age_days' => env('DEVELOPER_PRODUCTION_KYC_MAX_AGE_DAYS', 0),
        'organization_enabled' => env('DEVELOPER_ORGANIZATION_PRODUCTION_ACCESS_ENABLED', false),
        'require_two_factor_for_keys' => env('DEVELOPER_PRODUCTION_REQUIRE_2FA', true),
        'withdrawal_dual_control' => env('DEVELOPER_PRODUCTION_WITHDRAWAL_DUAL_CONTROL', true),
    ],
    'sandbox_faucet' => [
        'USDT' => '10000.00000000',
        'BTC' => '1.00000000',
        'ETH' => '10.00000000',
        'SOL' => '100.00000000',
    ],
    'permissions' => [
        'market.read',
        'account.read',
        'spot.read',
        'spot.trade',
        'futures.read',
        'futures.trade',
        'margin.read',
        'margin.trade',
        'margin.manage',
        'convert.read',
        'convert.execute',
        'wallet.read',
        'wallet.transfer',
        'wallet.withdraw',
        'staking.read',
        'staking.execute',
        'staking.manage',
        'copy.read',
        'copy.execute',
        'copy.manage',
        'p2p.read',
        'p2p.trade',
        'fiat.read',
        'fiat.deposit',
        'fiat.payout',
        'exapay.read',
        'exapay.write',
        'exapay.refunds',
        'exapay.manage',
        'giftcard.read',
        'giftcard.trade',
        'exaai.read',
        'exaai.execute',
        'exaai.manage',
        'webhooks.manage',
    ],
    'scope_registry' => [
        'market.read' => ['name'=>'Market data','description'=>'Read public market data.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>false],
        'account.read' => ['name'=>'Account','description'=>'Read account state.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'spot.read' => ['name'=>'Spot read','description'=>'Read Spot orders and trades.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'spot.trade' => ['name'=>'Spot trade','description'=>'Submit and cancel Spot orders.','risk'=>'WRITE','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'futures.read' => ['name'=>'Futures read','description'=>'Read Futures state.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'futures.trade' => ['name'=>'Futures trade','description'=>'Submit risk-checked Futures orders.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'margin.read' => ['name'=>'Margin read','description'=>'Read Margin state.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'margin.trade' => ['name'=>'Margin trade','description'=>'Submit Margin orders.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'margin.manage' => ['name'=>'Margin manage','description'=>'Borrow and repay Margin liabilities.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'convert.read' => ['name'=>'Convert read','description'=>'Read Convert quotes and history.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'convert.execute' => ['name'=>'Convert execute','description'=>'Execute Convert quotes.','risk'=>'WRITE','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'wallet.read' => ['name'=>'Wallet read','description'=>'Read balances and wallet history.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'wallet.transfer' => ['name'=>'Wallet transfer','description'=>'Create internal transfers.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'wallet.withdraw' => ['name'=>'Wallet withdrawal','description'=>'Create restricted withdrawals.','risk'=>'RESTRICTED','environments'=>['sandbox','production'],'product_status'=>'RESTRICTED','production_approval_required'=>true,'ip_required'=>true],
        'staking.read' => ['name'=>'Staking read','description'=>'Read staking products and positions.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'staking.execute' => ['name'=>'Staking execute','description'=>'Create staking actions.','risk'=>'WRITE','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'staking.manage' => ['name'=>'Staking manage','description'=>'Manage staking positions.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'copy.read' => ['name'=>'Copy read','description'=>'Read Copy Trading state.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'copy.execute' => ['name'=>'Copy execute','description'=>'Create Copy Trading actions.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'copy.manage' => ['name'=>'Copy manage','description'=>'Manage Copy Trading relationships.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'p2p.read' => ['name'=>'P2P read','description'=>'Read P2P resources.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'p2p.trade' => ['name'=>'P2P trade','description'=>'Create P2P actions.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'fiat.read' => ['name'=>'Fiat read','description'=>'Read Fiat resources.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'fiat.deposit' => ['name'=>'Fiat deposit','description'=>'Create Fiat deposits.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'fiat.payout' => ['name'=>'Fiat payout','description'=>'Create restricted Fiat payouts.','risk'=>'RESTRICTED','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true,'ip_required'=>true],
        'exapay.read' => ['name'=>'ExaPay read','description'=>'Read merchant payment state.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'exapay.write' => ['name'=>'ExaPay write','description'=>'Create merchant payment actions.','risk'=>'WRITE','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'exapay.refunds' => ['name'=>'ExaPay refunds','description'=>'Create payment refunds.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'exapay.manage' => ['name'=>'ExaPay manage','description'=>'Manage merchant payment configuration.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
        'giftcard.read' => ['name'=>'Giftcard read','description'=>'Read Giftcard resources.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'giftcard.trade' => ['name'=>'Giftcard trade','description'=>'Create Giftcard actions.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'exaai.read' => ['name'=>'ExaAI read','description'=>'Read ExaAI resources.','risk'=>'READ','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'exaai.execute' => ['name'=>'ExaAI execute','description'=>'Create governed ExaAI actions.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'exaai.manage' => ['name'=>'ExaAI manage','description'=>'Manage governed ExaAI resources.','risk'=>'HIGH','environments'=>['sandbox','production'],'product_status'=>'PRIVATE_BETA','production_approval_required'=>true],
        'webhooks.manage' => ['name'=>'Webhooks','description'=>'Manage project webhook endpoints.','risk'=>'WRITE','environments'=>['sandbox','production'],'product_status'=>'AVAILABLE','production_approval_required'=>true],
    ],
    'rate_limits' => [
        'public_per_minute' => 240,
        'private_per_minute' => 120,
        'trade_per_minute' => 60,
        'withdrawal_per_minute' => 10,
    ],
    'websocket' => [
        'redis_channel'=>'exaearn.developer.realtime',
        'heartbeat_seconds' => 30,
        'max_subscriptions' => 100,
        'queue_limit' => 1000,
        'replay_limit' => 500,
        'allowed_topics' => [
            'market.*',
            'account.balance',
            'order',
            'trade',
            'position',
            'margin',
            'deposit',
            'withdrawal',
            'staking',
            'copy',
            'exaai',
        ],
    ],
    'webhooks' => [
        'timeout_seconds' => 5,
        'max_attempts' => 8,
        'claim_lease_seconds' => 60,
        'max_payload_bytes' => 65536,
        'allowed_ports' => [443],
        'production_delivery_enabled' => env('DEVELOPER_PRODUCTION_WEBHOOK_DELIVERY_ENABLED', false),
        'production_egress_verified' => env('DEVELOPER_PRODUCTION_WEBHOOK_EGRESS_VERIFIED', false),
        'events' => [
            'order.filled',
            'order.cancelled',
            'deposit.completed',
            'withdrawal.completed',
            'withdrawal.failed',
            'transfer.completed',
            'copy.event',
            'exaai.event',
            'payment.created',
            'payment.processing',
            'payment.captured',
            'payment.failed',
            'payment.refunded',
            'payment.partially_refunded',
            'dispute.created',
            'dispute.updated',
            'settlement.created',
            'settlement.completed',
            'settlement.failed',
        ],
    ],
    'api_status' => [
        'spot' => 'AVAILABLE',
        'futures' => 'PRIVATE_BETA',
        'margin' => 'PRIVATE_BETA',
        'convert' => 'AVAILABLE',
        'wallet' => 'AVAILABLE',
        'staking' => 'AVAILABLE',
        'copy' => 'PRIVATE_BETA',
        'exaai' => 'PRIVATE_BETA',
    ],
];
