<?php

declare(strict_types=1);

return [
    'production_enabled' => (bool) env('FIAT_PRODUCTION_ENABLED', false),
    'low_capital_mode' => (bool) env('FIAT_LOW_CAPITAL_MODE', true),

    'currencies' => [
        'NGN' => [
            'name' => 'Nigerian Naira',
            'precision' => 2,
            'deposit_enabled' => true,
            'withdrawal_enabled' => true,
            'convert_enabled' => true,
            'p2p_enabled' => true,
            'minimum_deposit' => env('FIAT_NGN_MIN_DEPOSIT', '100'),
            'maximum_deposit' => env('FIAT_NGN_MAX_DEPOSIT', '10000000'),
            'minimum_withdrawal' => env('FIAT_NGN_MIN_WITHDRAWAL', '1000'),
            'maximum_withdrawal' => env('FIAT_NGN_MAX_WITHDRAWAL', '5000000'),
            'daily_limit' => env('FIAT_NGN_DAILY_LIMIT', '10000000'),
            'status' => env('FIAT_NGN_STATUS', 'CONFIGURATION_REQUIRED'),
            'countries' => ['NG'],
        ],
        'USD' => [
            'name' => 'United States Dollar',
            'precision' => 2,
            'deposit_enabled' => true,
            'withdrawal_enabled' => true,
            'convert_enabled' => true,
            'p2p_enabled' => false,
            'minimum_deposit' => env('FIAT_USD_MIN_DEPOSIT', '10'),
            'maximum_deposit' => env('FIAT_USD_MAX_DEPOSIT', '100000'),
            'minimum_withdrawal' => env('FIAT_USD_MIN_WITHDRAWAL', '10'),
            'maximum_withdrawal' => env('FIAT_USD_MAX_WITHDRAWAL', '100000'),
            'daily_limit' => env('FIAT_USD_DAILY_LIMIT', '100000'),
            'status' => env('FIAT_USD_STATUS', 'CONFIGURATION_REQUIRED'),
            'countries' => ['US'],
        ],
        'EUR' => [
            'name' => 'Euro',
            'precision' => 2,
            'deposit_enabled' => false,
            'withdrawal_enabled' => false,
            'convert_enabled' => false,
            'p2p_enabled' => false,
            'minimum_deposit' => '10',
            'maximum_deposit' => '100000',
            'minimum_withdrawal' => '10',
            'maximum_withdrawal' => '100000',
            'daily_limit' => '100000',
            'status' => env('FIAT_EUR_STATUS', 'DISABLED'),
            'countries' => ['EU'],
        ],
        'GBP' => [
            'name' => 'British Pound Sterling',
            'precision' => 2,
            'deposit_enabled' => false,
            'withdrawal_enabled' => false,
            'convert_enabled' => false,
            'p2p_enabled' => false,
            'minimum_deposit' => '10',
            'maximum_deposit' => '100000',
            'minimum_withdrawal' => '10',
            'maximum_withdrawal' => '100000',
            'daily_limit' => '100000',
            'status' => env('FIAT_GBP_STATUS', 'DISABLED'),
            'countries' => ['GB'],
        ],
        'ZAR' => [
            'name' => 'South African Rand',
            'precision' => 2,
            'deposit_enabled' => true,
            'withdrawal_enabled' => false,
            'convert_enabled' => true,
            'p2p_enabled' => false,
            'minimum_deposit' => '100',
            'maximum_deposit' => '1000000',
            'minimum_withdrawal' => '100',
            'maximum_withdrawal' => '1000000',
            'daily_limit' => '1000000',
            'status' => env('FIAT_ZAR_STATUS', 'CONFIGURATION_REQUIRED'),
            'countries' => ['ZA'],
        ],
    ],

    'providers' => [
        'sandbox' => [
            'name' => 'Sandbox Provider',
            'state' => env('FIAT_SANDBOX_STATE', 'SANDBOX'),
            'countries' => ['NG', 'US', 'ZA'],
            'currencies' => ['NGN', 'USD', 'ZAR'],
            'capabilities' => [
                'banks' => true,
                'account_verification' => true,
                'virtual_accounts' => true,
                'checkout' => true,
                'transfers' => true,
                'settlements' => true,
                'refunds' => true,
            ],
            'priority' => 999,
        ],
        'flutterwave' => [
            'name' => 'Flutterwave',
            'state' => env('FLUTTERWAVE_SECRET_KEY') ? env('FLUTTERWAVE_STATE', 'TESTING') : 'CREDENTIALS_REQUIRED',
            'countries' => ['NG', 'US', 'ZA'],
            'currencies' => ['NGN', 'USD', 'ZAR'],
            'capabilities' => ['banks' => true, 'account_verification' => true, 'virtual_accounts' => false, 'checkout' => true, 'transfers' => true, 'settlements' => true, 'refunds' => true],
            'priority' => 100,
        ],
        'nomba' => [
            'name' => 'Nomba',
            'state' => env('NOMBA_SECRET_KEY') ? env('NOMBA_STATE', 'TESTING') : 'CREDENTIALS_REQUIRED',
            'countries' => ['NG'],
            'currencies' => ['NGN'],
            'capabilities' => ['banks' => true, 'account_verification' => true, 'virtual_accounts' => true, 'checkout' => false, 'transfers' => true, 'settlements' => true, 'refunds' => false],
            'priority' => 90,
        ],
        'paystack' => [
            'name' => 'Paystack',
            'state' => env('PAYSTACK_SECRET_KEY') ? env('PAYSTACK_STATE', 'TESTING') : 'CREDENTIALS_REQUIRED',
            'countries' => ['NG'],
            'currencies' => ['NGN'],
            'capabilities' => ['banks' => true, 'account_verification' => true, 'virtual_accounts' => true, 'checkout' => true, 'transfers' => true, 'settlements' => true, 'refunds' => true],
            'priority' => 110,
        ],
    ],

    'fees' => [
        'deposit_percent' => env('FIAT_DEPOSIT_PERCENT_FEE', '0'),
        'deposit_flat' => env('FIAT_DEPOSIT_FLAT_FEE', '0'),
        'withdrawal_percent' => env('FIAT_WITHDRAWAL_PERCENT_FEE', '0.005'),
        'withdrawal_flat' => env('FIAT_WITHDRAWAL_FLAT_FEE', '0'),
        'merchant_percent' => env('EXAEARN_PAY_MERCHANT_PERCENT_FEE', '0.01'),
    ],

    'risk' => [
        'large_withdrawal_threshold' => env('FIAT_LARGE_WITHDRAWAL_THRESHOLD', '1000000'),
        'velocity_window_minutes' => (int) env('FIAT_VELOCITY_WINDOW_MINUTES', 60),
        'velocity_count_threshold' => (int) env('FIAT_VELOCITY_COUNT_THRESHOLD', 5),
    ],
];
